### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by martinlemahieu** [martinlemahieu/imageboard#4]
## V1

**Client**

- [ ] upload (queue + send requests + handle responses + update statuses)

- [ ] edit tags on existing image

- [ ] set global data for upload batch (purity, tags)

- [ ] set individual data for upload (purity, tags)

- [ ] user menu

- [ ] security (register/login/firewall/tokens)

**Server** 

- [ ] upload (handle errors + handle file + extract metadata like size, weight, type + return correct responses)

- [ ] crud tags endpoints

- [ ] add/remove tags to images

- [ ] security (register/login/tokens)

- [ ] users (owns images, log user activity ...)
